
"""
Leakage test for volume_ma_20min
Generated by Feature Store Leakage Firewall
"""

import pytest
import pandas as pd
import numpy as np

def test_volume_ma_20min_no_leakage():
    """Test that volume_ma_20min does not introduce lookahead bias."""
    
    # Create test data with known future values
    test_data = pd.DataFrame({
        'timestamp': pd.date_range('2025-01-01', periods=100, freq='1min'),
        'price': np.random.randn(100).cumsum() + 100,
        'volume': np.random.randint(1000, 10000, 100)
    })
    
    # Apply feature definition
    feature_definition = """df['volume'].rolling(20).mean()"""
    
    # Test that feature doesn't use future data
    # This test will fail if the feature uses .shift(-1) or similar
    result = eval(feature_definition)
    
    # Verify no NaN values at the beginning (indicating future data usage)
    assert not result.iloc[:10].isna().any(), "Feature uses future data"
    
    # Verify feature is properly lagged
    expected_lag = max([20]) if [20] else 0
    if expected_lag > 0:
        assert result.iloc[:expected_lag].isna().all(), "Feature not properly lagged"
    
    print(f"PASSED volume_ma_20min leakage test")

