@echo off
echo Starting XRP Bot with V8 Emergency Fixes...

set V8_MICROSTRUCTURE_SPREAD_CAP=0.0025
set V8_MICROSTRUCTURE_IMBALANCE_GATE=0.15
set EMERGENCY_MICROSTRUCTURE_BYPASS=false
set V8_POSITION_LOSS_THRESHOLD=0.05
set BOT_CONFIDENCE_THRESHOLD=0.005
set BOT_DISABLE_MICRO_ACCOUNT_SAFEGUARD=true
set BOT_MIN_PNL_THRESHOLD=0.001
set BOT_BYPASS_INTERACTIVE=true

echo Environment variables set:
echo V8_MICROSTRUCTURE_SPREAD_CAP=%V8_MICROSTRUCTURE_SPREAD_CAP%
echo V8_MICROSTRUCTURE_IMBALANCE_GATE=%V8_MICROSTRUCTURE_IMBALANCE_GATE%
echo EMERGENCY_MICROSTRUCTURE_BYPASS=%EMERGENCY_MICROSTRUCTURE_BYPASS%
echo V8_POSITION_LOSS_THRESHOLD=%V8_POSITION_LOSS_THRESHOLD%
echo BOT_CONFIDENCE_THRESHOLD=%BOT_CONFIDENCE_THRESHOLD%
echo BOT_DISABLE_MICRO_ACCOUNT_SAFEGUARD=%BOT_DISABLE_MICRO_ACCOUNT_SAFEGUARD%
echo BOT_MIN_PNL_THRESHOLD=%BOT_MIN_PNL_THRESHOLD%
echo BOT_BYPASS_INTERACTIVE=%BOT_BYPASS_INTERACTIVE%

echo.
echo Starting bot with optimized parameters...
python newbotcode.py --fee_threshold_multi 0.5
