# Auto-generated config/constants
MIN_NOTIONAL = 10.0
HYPER_OPTIMIZED_MODE = True
WS_MAX_RECONNECT_ATTEMPTS = 5
WS_ERROR_SUPPRESSION_TIME = 60
WS_PING_INTERVAL = 30
EMAIL_ALERTS = False  # Set to True and configure below for email alerts
EMAIL_SENDER = "your_email@example.com"
EMAIL_PASSWORD = "your_password"
EMAIL_RECEIVER = "alert@example.com"
GROK_TP_TIERS = [0.01, 0.02, 0.03]  # 1%, 2%, 3% take profit tiers
GROK_TP_SIZES = [0.3, 0.3, 0.4]     # 30%, 30%, 40% of position
GROK_BREAKEVEN_ACTIVATION = 0.01    # Move SL to breakeven after 1% profit
GROK_TRAILING_ACTIVATION = 0.005    # Activate trailing after 0.5% profit
GROK_ATR_PERIOD = 14                # ATR period for dynamic stops
GROK_ATR_MULTIPLIER = 2.0           # ATR multiplier for stop loss
GROK_TRAILING_ATR_MULTIPLIER = 1.5  # ATR multiplier for trailing stop
EMERGENCY_STOP_LOSS_PCT = 0.005     # 0.5% stop loss (CRITICAL FIX)
EMERGENCY_MIN_TRADE_INTERVAL = 300  # 5 minutes between trades (CRITICAL FIX)
EMERGENCY_MAX_DAILY_TRADES = 50     # Max 50 trades per day (CRITICAL FIX)
EMERGENCY_MAX_CONSECUTIVE_LOSSES = 3 # Stop after 3 losses (CRITICAL FIX)
EMERGENCY_MIN_SIGNAL_STRENGTH = 0.7 # 70% minimum confidence (CRITICAL FIX)
EMERGENCY_MAX_DAILY_LOSS = 0.1      # 10% max daily loss (CRITICAL FIX)
EMERGENCY_BASE_POSITION_SIZE = 5.0  # Reduced position size (CRITICAL FIX)
EMERGENCY_MAX_POSITION_SIZE = 10.0  # Cap maximum position (CRITICAL FIX)
GROK_COMPOUND_ENABLED = True
GROK_BASE_POSITION_SIZE = 5.0       # EMERGENCY: Reduced from 50.0 to 5.0
GROK_COMPOUND_FACTOR = 1.1          # 10% increase per winning trade
GROK_MAX_POSITION_SIZE = 10.0       # EMERGENCY: Reduced from 500.0 to 10.0
GROK_RISK_PER_TRADE = 0.02          # 2% risk per trade
GROK_PERFORMANCE_TRACKING = True
GROK_ADAPTATION_INTERVAL = 3600     # Adapt parameters every hour
GROK_MIN_TRADES_FOR_ADAPTATION = 10 # Minimum trades before adapting
GROK_WIN_RATE_THRESHOLD = 0.4       # 40% minimum win rate
GROK_PROFIT_THRESHOLD = 0.001       # 0.1% minimum profit for positive learning
