name: Artifact Freshness Guard

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-artifact-freshness:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Artifact Freshness
      run: |
        python scripts/check_artifact_staleness.py
    
    - name: Upload staleness check logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: artifact-freshness-logs
        path: |
          reports/tests/artifact_freshness_check.json
        retention-days: 30