name: Daily Backtest & Artifact Generation

on:
  schedule:
    # Run daily at 6 AM UTC (after market close)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ master ]
    paths:
      - 'src/core/strategies/**'
      - 'src/core/backtesting/**'
      - 'config/**'

jobs:
  daily-backtest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_ultimate.txt
        
    - name: Run Comprehensive Backtest
      run: |
        python scripts/run_comprehensive_backtest.py \
          --start-date 2024-01-01 \
          --end-date 2024-12-31 \
          --initial-capital 10000 \
          --output-dir reports/daily_backtests/$(date +%Y%m%d)
          
    - name: Generate Executive Dashboard
      run: |
        python src/core/analytics/executive_dashboard.py
        
    - name: Update Trade Ledger
      run: |
        python scripts/update_trade_ledger.py \
          --input-dir reports/daily_backtests/$(date +%Y%m%d) \
          --output reports/ledgers/trades_$(date +%Y%m%d).parquet
          
    - name: Generate Performance Report
      run: |
        python scripts/generate_performance_report.py \
          --date $(date +%Y%m%d) \
          --output reports/performance/daily_$(date +%Y%m%d).html
          
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backtest-artifacts-${{ github.run_number }}
        path: |
          reports/daily_backtests/
          reports/ledgers/
          reports/tearsheets/
          reports/performance/
          reports/executive_dashboard.html
        retention-days: 30
        
    - name: Commit Results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/
        git commit -m "🤖 Daily Backtest Results $(date +%Y-%m-%d)

        📊 Generated Artifacts:
        - Daily backtest results for $(date +%Y-%m-%d)
        - Updated trade ledger with latest trades
        - Executive dashboard with performance metrics
        - Performance report with attribution analysis
        
        🎯 Performance Summary:
        - Total trades: $(grep -o '"total_trades": [0-9]*' reports/performance/daily_$(date +%Y%m%d).html | cut -d' ' -f2)
        - Total return: $(grep -o '"total_return": [0-9.-]*' reports/performance/daily_$(date +%Y%m%d).html | cut -d' ' -f2)
        - Sharpe ratio: $(grep -o '"sharpe_ratio": [0-9.-]*' reports/performance/daily_$(date +%Y%m%d).html | cut -d' ' -f2)
        
        Generated by GitHub Actions on $(date)" || echo "No changes to commit"
        
    - name: Push Results
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: false
